ALTER TABLE ai_conversation_questions
ADD COLUMN IF NOT EXISTS advance_policy VARCHAR(50) NOT NULL DEFAULT 'ON_CORRECT_ONLY',
ADD COLUMN IF NOT EXISTS allow_skip BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS skip_after_attempts INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS retry_prompt_text TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS correct_feedback TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS retry_feedback TEXT DEFAULT NULL;

ALTER TABLE ai_conversation_questions
ADD CONSTRAINT ck_advance_policy CHECK (advance_policy IN ('ON_CORRECT_ONLY', 'AFTER_MAX_ATTEMPTS', 'MANUAL_SKIP_ONLY'));
