ALTER TABLE npcs ADD COLUMN animation_url TEXT;
ALTER TABLE npcs ADD COLUMN role TEXT;
ALTER TABLE npcs ADD COLUMN personality TEXT;
ALTER TABLE npcs ADD COLUMN skill_tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE npcs ADD COLUMN program_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE npcs ADD COLUMN path_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE npcs ADD COLUMN unlock_benefit TEXT;
ALTER TABLE npcs ADD COLUMN access_type TEXT NOT NULL DEFAULT 'FREE';
