-- Fix learning_paths missing columns
ALTER TABLE learning_paths ADD COLUMN IF NOT EXISTS target_profile_rules JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE learning_paths ADD COLUMN IF NOT EXISTS level TEXT NOT NULL DEFAULT 'BEGINNER';
ALTER TABLE learning_paths ADD COLUMN IF NOT EXISTS access_type TEXT NOT NULL DEFAULT 'FREE';

-- Fix lessons missing columns
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS level TEXT NOT NULL DEFAULT 'BEGINNER';
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS difficulty_categories JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS learning_goals JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS publish_status TEXT NOT NULL DEFAULT 'DRAFT';

-- Fix programs missing columns
ALTER TABLE programs ADD COLUMN IF NOT EXISTS target_age_min INT NOT NULL DEFAULT 2;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS target_age_max INT NOT NULL DEFAULT 6;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS difficulty_categories JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS learning_goals JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS skill_tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE programs ADD COLUMN IF NOT EXISTS level TEXT NOT NULL DEFAULT 'BEGINNER';
ALTER TABLE programs ADD COLUMN IF NOT EXISTS access_type TEXT NOT NULL DEFAULT 'FREE';

-- Add missing activities columns
ALTER TABLE activities ADD COLUMN IF NOT EXISTS tts_prompt_text TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS media_refs JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS retry_limit INT NOT NULL DEFAULT 3;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS voice_premium_required BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS parent_instruction TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS source_library TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS source_collection TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS source_id TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS source_lesson_id UUID REFERENCES lessons(id) ON DELETE SET NULL;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS source_snapshot JSONB;
