// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_K3RYCeYvgC-qt-Umcpb4_ez2F4fEhY',
    appId: '1:543274803579:web:0e36ec7f2e24bcc0a09dde',
    messagingSenderId: '543274803579',
    projectId: 'project-ha152',
    authDomain: 'project-ha152.firebaseapp.com',
    databaseURL: 'https://project-ha152-default-rtdb.firebaseio.com',
    storageBucket: 'project-ha152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1T5h-IWx8flSqQmjMPR3NlFsZB6ClPo',
    appId: '1:543274803579:android:03b632d67560ce09a09dde',
    messagingSenderId: '543274803579',
    projectId: 'project-ha152',
    databaseURL: 'https://project-ha152-default-rtdb.firebaseio.com',
    storageBucket: 'project-ha152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgTswnNJm25GywuV5z633SGR-8Qa45u0',
    appId: '1:543274803579:ios:6481eb6275356d6ea09dde',
    messagingSenderId: '543274803579',
    projectId: 'project-ha152',
    databaseURL: 'https://project-ha152-default-rtdb.firebaseio.com',
    storageBucket: 'project-ha152.firebasestorage.app',
    iosClientId:
        '543274803579-vma79e220gfda1r67b13q4rm86ull2l6.apps.googleusercontent.com',
    iosBundleId: 'com.projectha.mobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgTswnNJm25GywuV5z633SGR-8Qa45u0',
    appId: '1:543274803579:ios:6481eb6275356d6ea09dde',
    messagingSenderId: '543274803579',
    projectId: 'project-ha152',
    databaseURL: 'https://project-ha152-default-rtdb.firebaseio.com',
    storageBucket: 'project-ha152.firebasestorage.app',
    iosClientId:
        '543274803579-vma79e220gfda1r67b13q4rm86ull2l6.apps.googleusercontent.com',
    iosBundleId: 'com.projectha.mobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_K3RYCeYvgC-qt-Umcpb4_ez2F4fEhY',
    appId: '1:543274803579:web:04dc06021d89b32fa09dde',
    messagingSenderId: '543274803579',
    projectId: 'project-ha152',
    authDomain: 'project-ha152.firebaseapp.com',
    databaseURL: 'https://project-ha152-default-rtdb.firebaseio.com',
    storageBucket: 'project-ha152.firebasestorage.app',
  );
}
